name: "OpenClaw Hook Trigger"
description: "Trigger OpenClaw webhook hooks from GitHub Actions (wake or agent), with optional legacy raw payload mode"
author: "harvbot"
inputs:
  hook_url:
    description: "OpenClaw hook endpoint URL (for example: https://host/hooks/wake or /hooks/agent)"
    required: false
  notify_url:
    description: "Legacy alias for hook_url"
    required: false
  shared_secret:
    description: "Hook token sent as Authorization bearer token"
    required: true
  mode:
    description: "Payload mode: openclaw-wake, openclaw-agent, or raw"
    required: false
    default: "openclaw-wake"
  wake_mode:
    description: "Wake mode for OpenClaw hooks: now or next-heartbeat"
    required: false
    default: "now"
  event_name:
    description: "Event label used in generated text"
    required: false
    default: "repo.pull.request"
  extra_context:
    description: "Optional freeform context string"
    required: false
  agent_name:
    description: "Name field for /hooks/agent payload"
    required: false
    default: "GitHub"
  timeout_seconds:
    description: "HTTP timeout in seconds"
    required: false
    default: "10"
outputs:
  delivered:
    description: "true if HTTP delivery succeeded"
    value: ${{ steps.send.outputs.delivered }}
runs:
  using: "composite"
  steps:
    - id: send
      shell: bash
      env:
        INPUT_HOOK_URL: ${{ inputs.hook_url }}
        INPUT_NOTIFY_URL: ${{ inputs.notify_url }}
        INPUT_SHARED_SECRET: ${{ inputs.shared_secret }}
        INPUT_MODE: ${{ inputs.mode }}
        INPUT_WAKE_MODE: ${{ inputs.wake_mode }}
        INPUT_EVENT_NAME: ${{ inputs.event_name }}
        INPUT_EXTRA_CONTEXT: ${{ inputs.extra_context }}
        INPUT_AGENT_NAME: ${{ inputs.agent_name }}
        INPUT_TIMEOUT_SECONDS: ${{ inputs.timeout_seconds }}
        GH_REPOSITORY: ${{ github.repository }}
        GH_REF_NAME: ${{ github.ref_name }}
        GH_SHA: ${{ github.sha }}
        GH_RUN_ID: ${{ github.run_id }}
        GH_RUN_ATTEMPT: ${{ github.run_attempt }}
        GH_ACTOR: ${{ github.actor }}
        GH_SERVER_URL: ${{ github.server_url }}
      run: |
        set -euo pipefail

        URL="${INPUT_HOOK_URL:-}"
        if [ -z "$URL" ]; then
          URL="${INPUT_NOTIFY_URL:-}"
        fi
        if [ -z "$URL" ]; then
          echo "hook_url (or legacy notify_url) is required" >&2
          exit 1
        fi

        payload=$(python3 - <<'PY'
import json, os
mode = (os.environ.get("INPUT_MODE") or "openclaw-wake").strip().lower()
repo = os.environ.get("GH_REPOSITORY")
branch = os.environ.get("GH_REF_NAME")
sha = os.environ.get("GH_SHA")
actor = os.environ.get("GH_ACTOR")
run_id = os.environ.get("GH_RUN_ID")
server = os.environ.get("GH_SERVER_URL")
event = os.environ.get("INPUT_EVENT_NAME", "repo.pull.request")
extra = (os.environ.get("INPUT_EXTRA_CONTEXT") or "").strip()
run_url = f"{server}/{repo}/actions/runs/{run_id}"

text = f"[{event}] {repo} {branch} updated to {sha} by {actor}. Run: {run_url}"
if extra:
  text += f" | context: {extra}"

if mode == "openclaw-agent":
  payload = {
    "message": text,
    "name": os.environ.get("INPUT_AGENT_NAME", "GitHub"),
    "wakeMode": os.environ.get("INPUT_WAKE_MODE", "now"),
  }
elif mode == "raw":
  payload = {
    "event": event,
    "repo": repo,
    "branch": branch,
    "sha": sha,
    "actor": actor,
    "run_id": run_id,
    "run_attempt": os.environ.get("GH_RUN_ATTEMPT"),
    "run_url": run_url,
  }
  if extra:
    payload["context"] = extra
else:
  payload = {
    "text": text,
    "mode": os.environ.get("INPUT_WAKE_MODE", "now"),
  }

print(json.dumps(payload, separators=(",",":")))
PY
)

        curl --fail --show-error --silent \
          --max-time "${INPUT_TIMEOUT_SECONDS}" \
          -X POST "$URL" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${INPUT_SHARED_SECRET}" \
          --data "$payload" >/dev/null

        echo "delivered=true" >> "$GITHUB_OUTPUT"
